on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GLOBAL_VAR: "Essa é uma variável global"

    steps:
    - name: Checkout no Repo
      uses: actions/checkout@v4

    - name: Printando a variável
      run: echo ${{ env.GLOBAL_VAR }}

    - name: Definindo a variável no nível do job
      run: |
        JOB_VAR="Giropops no job-level!"
        echo "JOB_VAR=$JOB_VAR" >> $GITHUB_ENV

    - name: Printando a variável no nível do job
      run: echo ${{ env.JOB_VAR }}

    - name: Definindo uma variável no nível do step
      run: |
        STEP_VAR="Giropops no step-level"
        echo "STEP_VAR=$STEP_VAR" >> $GITHUB_ENV

    - name: Printando a variável no nível do step
      run: echo ${{ env.STEP_VAR }}
